modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"
issueTrackerURL = "https://github.com/honononta-2/Version-World-Sorter/issues"
logoFile = "icon.png"

[[mods]]
modId = "version_world_sorter"
version = "${version}"
displayName = "Version World Sorter"
description = "Hides save worlds that don't match the current Minecraft version from the world selection screen."
authors = "honononta-2"
displayURL = "https://github.com/honononta-2/Version-World-Sorter"

[[dependencies.version_world_sorter]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.5,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.version_world_sorter]]
modId = "neoforge"
type = "required"
versionRange = "[20.5,)"
ordering = "NONE"
side = "CLIENT"
